namespace: dev

movieService:
  image:
    repository: damdam1977/movie-service
    pullPolicy: IfNotPresent
    # Tag will be override by the BUILD_ID in Jenkinsfile
    tag: ""
  replicas: 1
  databaseUri: postgresql://movie_db_user_dev:movie_db_password_dev@movie-db.dev.svc.cluster.local/movie_db_dev
  castServiceHostUrl: "http://cast-service.dev.svc.cluster.local:8000/api/v1/casts/"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

movieDb:
  postgresUser: movie_db_user_dev
  postgresPassword: movie_db_password_dev
  postgresDb: movie_db_dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

castService:
  image:
    repository: damdam1977/cast-service
    pullPolicy: IfNotPresent
    # Tag will be override by the BUILD_ID in Jenkinsfile
    tag: ""
  replicas: 1
  databaseUri: postgresql://cast_db_user_dev:cast_db_password_dev@cast-db.dev.svc.cluster.local/cast_db_dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

castDb:
  postgresUser: cast_db_user_dev
  postgresPassword: cast_db_password_dev
  postgresDb: cast_db_dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
