namespace: prod

movieService:
  image:
    repository: damdam1977/movie-service
    pullPolicy: IfNotPresent
    # Tag will be override by the BUILD_ID in Jenkinsfile
    tag: ""
  replicas: 1
  databaseUri: postgresql://movie_db_user_prod:movie_db_password_prod@movie-db.prod.svc.cluster.local/movie_db_prod
  castServiceHostUrl: "http://cast-service.prod.svc.cluster.local:8000/api/v1/casts/"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 3
    cpuUtilizationPercentage: 60

movieDb:
  postgresUser: movie_db_user_prod
  postgresPassword: movie_db_password_prod
  postgresDb: movie_db_prod
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

castService:
  image:
    repository: damdam1977/cast-service
    pullPolicy: IfNotPresent
    # Tag will be override by the BUILD_ID in Jenkinsfile
    tag: ""
  replicas: 1
  databaseUri: postgresql://cast_db_user_prod:cast_db_password_prod@cast-db.prod.svc.cluster.local/cast_db_prod
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

castDb:
  postgresUser: cast_db_user_prod
  postgresPassword: cast_db_password_prod
  postgresDb: cast_db_prod
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
