namespace: qa

movieService:
  image:
    repository: damdam1977/movie-service
    pullPolicy: IfNotPresent
    tag: ""
  replicas: 1
  databaseUri: postgresql://movie_db_user_qa:movie_db_password_qa@movie-db.qa.svc.cluster.local/movie_db_qa
  castServiceHostUrl: "http://cast-service.qa.svc.cluster.local:8000/api/v1/casts/"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 3
    cpuUtilizationPercentage: 60

movieDb:
  postgresUser: movie_db_user_qa
  postgresPassword: movie_db_password_qa
  postgresDb: movie_db_qa
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

castService:
  image:
    repository: damdam1977/cast-service
    pullPolicy: IfNotPresent
    tag: ""
  replicas: 1
  databaseUri: postgresql://cast_db_user_qa:cast_db_password_qa@cast-db.qa.svc.cluster.local/cast_db_qa
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

castDb:
  postgresUser: cast_db_user_qa
  postgresPassword: cast_db_password_qa
  postgresDb: cast_db_qa
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
