namespace: staging

movieService:
  image:
    repository: damdam1977/movie-service
    pullPolicy: IfNotPresent
    tag: v.1.0
  replicas: 1
  databaseUri: postgresql://movie_db_user_staging:movie_db_password_staging@movie-db.staging.svc.cluster.local/movie_db_staging
  castServiceHostUrl: "http://cast-service.staging.svc.cluster.local:8000/api/v1/casts/"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 3
    cpuUtilizationPercentage: 60

movieDb:
  postgresUser: movie_db_user_staging
  postgresPassword: movie_db_password_staging
  postgresDb: movie_db_staging
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

castService:
  image:
    repository: damdam1977/cast-service
    pullPolicy: IfNotPresent
    tag: v.1.0
  replicas: 1
  databaseUri: postgresql://cast_db_user_staging:cast_db_password_staging@cast-db.staging.svc.cluster.local/cast_db_staging
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

castDb:
  postgresUser: cast_db_user_staging
  postgresPassword: cast_db_password_staging
  postgresDb: cast_db_staging
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
