namespace: dev

movieService:
  image: damdam1977/movie-service:1.0-dev
  replicas: 1
  databaseUri: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
  castServiceHostUrl: http://cast-service.dev.svc.cluster.local:8000/api/v1/casts/
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

movieDb:
  postgresUser: movie_db_username
  postgresPassword: movie_db_password
  postgresDb: movie_db_dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

castService:
  image: damdam1977/cast-service:1.0-dev
  replicas: 1
  databaseUri: postgresql://cast_db_username:cast_db_password@cast-db.dev.svc.cluster.local/cast_db_dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationPercentage: 60

castDb:
  postgresUser: cast_db_username
  postgresPassword: cast_db_password
  postgresDb: cast_db_dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

nginx:
  image: nginx:latest
  port: 8080
