apiVersion: v1
kind: Secret
metadata:
  name: cast-db-credentials-qa
  namespace: qa
type: Opaque
data:
  castDatabaseUri: cG9zdGdyZXNxbDovL2Nhc3RfZGJfdXNlcl9xYTpjYXN0X2RiX3Bhc3N3b3JkX3FhQGNhc3QtZGIucWEuc3ZjLmNsdXN0ZXIubG9jYWwvY2FzdF9kYl9xYQ==  # postgresql://cast_db_user_qa:cast_db_password_qa@cast-db.qa.svc.cluster.local/cast_db_qa
  POSTGRES_USER: Y2FzdF9kYl91c2VyX3Fh  # cast_db_user_qa
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZF9xYQ==  # cast_db_password_qa
  POSTGRES_DB: Y2FzdF9kYl9xYQ==  # cast_db_qa
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  namespace: qa
spec:
  serviceName: "cast-db-headless"
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-qa
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-qa
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-qa
                  key: POSTGRES_DB
          volumeMounts:
            - name: cast-db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: cast-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-headless
  namespace: qa
spec:
  clusterIP: None
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432
