apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-qa
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: damdam1977/movie-service:1.0-prod
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: movie-db-credentials-qa
                  key: databaseUri
            - name: CAST_SERVICE_HOST_URL
              valueFrom:
                configMapKeyRef:
                  name: movie-config-qa
                  key: CAST_SERVICE_HOST_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: qa
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8000
  selector:
    app: movie-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-service-hpa
  namespace: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
