apiVersion: v1
kind: Secret
metadata:
  name: movie-db-credentials-dev
  namespace: dev
type: Opaque
data:
  databaseUri: cG9zdGdyZXNxbDovL21vdmllX2RiX3VzZXJfZGV2Om1vdmllX2RiX3Bhc3N3b3JkX2RldkBtb3ZpZS1kYi5kZXYuc3ZjLmNsdXN0ZXIubG9jYWwvbW92aWVfZGJfZGV2  # postgresql://movie_db_user_dev:movie_db_password_dev@movie-db.dev.svc.cluster.local/movie_db_dev
  POSTGRES_USER: bW92aWVfZGJfdXNlcl9kZXY=  # movie_db_user_dev
  POSTGRES_PASSWORD: bW92aWVfZGJfcGFzc3dvcmRfZGV2  # movie_db_password_dev
  POSTGRES_DB: bW92aWVfZGJfZGV2  # movie_db_dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config-dev
  namespace: dev
data:
  CAST_SERVICE_HOST_URL: "http://cast-service.dev.svc.cluster.local:8000/api/v1/casts/"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  namespace: dev
spec:
  serviceName: "movie-db-headless"  # Link to the Headless Service
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movie-db-credentials-dev
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-db-credentials-dev
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: movie-db-credentials-dev
                  key: POSTGRES_DB
          volumeMounts:
            - name: movie-db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  volumeClaimTemplates:
    - metadata:
        name: movie-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db-headless
  namespace: dev
spec:
  clusterIP: None  # This makes it a Headless Service
  selector:
    app: movie-db
  ports:
    - port: 5432
      targetPort: 5432