apiVersion: v1
kind: Secret
metadata:
  name: cast-db-credentials-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  castDatabaseUri: {{ .Values.castService.databaseUri | b64enc }}
  POSTGRES_USER: {{ .Values.castDb.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.castDb.postgresPassword | b64enc }}
  POSTGRES_DB: {{ .Values.castDb.postgresDb | b64enc }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "cast-db-headless"
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-{{ .Values.namespace }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-{{ .Values.namespace }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-{{ .Values.namespace }}
                  key: POSTGRES_DB
          volumeMounts:
            - name: cast-db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "{{ .Values.castDb.resources.requests.memory }}"
              cpu: "{{ .Values.castDb.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.castDb.resources.limits.memory }}"
              cpu: "{{ .Values.castDb.resources.limits.cpu }}"
  volumeClaimTemplates:
    - metadata:
        name: cast-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432
