apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.castService.image }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: cast-db-credentials-{{ .Values.namespace }}
                  key: castDatabaseUri
          resources:
            requests:
              memory: "{{ .Values.castService.resources.requests.memory }}"
              cpu: "{{ .Values.castService.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.castService.resources.limits.memory }}"
              cpu: "{{ .Values.castService.resources.limits.cpu }}"
          # livenessProbe:
            # httpGet:
            #   path: /healthz
            #   port: 8000
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8000
  selector:
    app: cast-service
