apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movieService.replicas }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: {{ .Values.movieService.image }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: movie-db-credentials-{{ .Values.namespace }}
                  key: databaseUri
            - name: CAST_SERVICE_HOST_URL
              valueFrom:
                configMapKeyRef:
                  name: movie-config-{{ .Values.namespace }}
                  key: CAST_SERVICE_HOST_URL
          resources:
            requests:
              memory: "{{ .Values.movieService.resources.requests.memory }}"
              cpu: "{{ .Values.movieService.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.movieService.resources.limits.memory }}"
              cpu: "{{ .Values.movieService.resources.limits.cpu }}"
          # livenessProbe:
            # httpGet:
            #   path: /healthz
            #   port: 8000
          # readinessProbe:
            # httpGet:
            #   path: /readiness
            #   port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8000
  selector:
    app: movie-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-service-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-service
  minReplicas: {{ .Values.movieService.hpa.minReplicas }}
  maxReplicas: {{ .Values.movieService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.movieService.hpa.cpuUtilizationPercentage }}
