apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ .Values.nginx.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config-{{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
      listen {{ .Values.nginx.port }};

      location /api/v1/movies {
        proxy_pass http://movie-service.{{ .Values.namespace }}.svc.cluster.local:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-service.{{ .Values.namespace }}.svc.cluster.local:8000/api/v1/casts;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
  selector:
    app: nginx
