apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  namespace: dev
spec:
  serviceName: "movie-db"
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          value: movie_db_username
        - name: POSTGRES_PASSWORD
          value: movie_db_password
        - name: POSTGRES_DB
          value: movie_db_dev
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
